apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: urlscrapper
  name: urlscrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlscrapper
  template:
    metadata:
      labels:
        app: urlscrapper
    spec:
      automountServiceAccountToken: false
      containers:
      - image: docker.io/sedjro/urlscraper:0.1
        name: urlscraper
        command: ["/bin/sh"]
        args: ["-c","/home/gopher/urlScraper -u \"https://linkchecker.github.io/\" -u \"https://redis-py.readthedocs.io/\" -o \"json\" && sleep infinity"]
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi